name: Demov1

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        git config --global url."git@github.com:".insteadOf "https://github.com/"

    - name: Install dependencies, configure SLURM, and run training
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
          set -e

          # Install required packages
          sudo apt update &&
          sudo apt install -y git python3 python3-pip python3-venv build-essential slurm-wlm munge &&

          # Get hostname and make sure it resolves
          HOSTNAME=$(hostname)
          echo "Detected hostname: $HOSTNAME"
          grep -q "127.0.0.1 $HOSTNAME" /etc/hosts || echo "127.0.0.1 $HOSTNAME" | sudo tee -a /etc/hosts

          # Ensure slurm user exists
          id slurm || sudo useradd -m slurm

          # Create slurm.conf using heredoc
          sudo mkdir -p /etc/slurm-llnl
          sudo bash -c "cat > /etc/slurm-llnl/slurm.conf" <<EOF
ControlMachine=$HOSTNAME
SlurmUser=slurm
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge
StateSaveLocation=/var/spool/slurm/state
SlurmdSpoolDir=/var/spool/slurmd
SwitchType=switch/none
MpiDefault=none
SlurmctldTimeout=300
SlurmdTimeout=300
SchedulerType=sched/backfill
SelectType=select/cons_res
SelectTypeParameters=CR_Core
NodeName=$HOSTNAME CPUs=2 State=UNKNOWN
PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP
EOF

          # Restart MUNGE and SLURM services
          sudo systemctl restart munge
          sudo systemctl restart slurmctld
          sudo systemctl restart slurmd

          # Go to project directory
          cd ${{ secrets.SSH_PATH }}
          [ -d Demo-ML-TF-Slurm ] || git clone git@github.com:okcan/Demo-ML-TF-Slurm.git
          cd Demo-ML-TF-Slurm

          # Set up Python venv
          [ -d venv ] || python3 -m venv venv
          source venv/bin/activate

          pip install --upgrade pip
          pip install torch pandas scikit-learn matplotlib

          # Run SLURM job
          sbatch train_job.slurm
        '
