name: Demo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        git config --global url."git@github.com:".insteadOf "https://github.com/"

    - name: Install dependencies, configure SLURM, and train model
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          set -e

          # Update and install dependencies
          sudo apt update &&
          sudo apt install -y git python3 python3-pip python3-venv build-essential slurm-wlm munge &&

          # Enable and start services
          sudo systemctl enable --now munge &&
          sudo systemctl enable --now slurmctld &&
          sudo systemctl enable --now slurmd &&

          # Generate basic slurm.conf for localhost (single-node config)
          sudo tee /etc/slurm-llnl/slurm.conf > /dev/null <<EOF
ControlMachine=localhost
SlurmUser=slurm
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge
StateSaveLocation=/var/spool/slurm/state
SlurmdSpoolDir=/var/spool/slurmd
SwitchType=switch/none
MpiDefault=none
SlurmctldTimeout=300
SlurmdTimeout=300
SchedulerType=sched/backfill
SelectType=select/cons_res
SelectTypeParameters=CR_Core

NodeName=localhost CPUs=2 State=UNKNOWN
PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP
EOF

          # Restart SLURM services after config
          sudo systemctl restart munge slurmctld slurmd &&

          # Project directory
          cd ${{ secrets.SSH_PATH }} &&

          # Clone repo if not present
          [ -d Demo-ML-TF-Slurm ] || git clone git@github.com:okcan/Demo-ML-TF-Slurm.git &&

          cd Demo-ML-TF-Slurm &&

          # Set up virtualenv
          [ -d venv ] || python3 -m venv venv
          source venv/bin/activate &&

          pip install --upgrade pip &&
          pip install torch pandas scikit-learn matplotlib &&

          # Run model training via SLURM
          sbatch train_job.slurm
        "
